routes/admin.php
<?php 

use App\Http\Controllers\Admin\AuthController;
// use App\Http\Controllers\Admin\CommentController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->name('admin.')->group(function() {
    Route::view('/login', 'auth.login'); 
    Route::post('/login', [AuthController::class, 'store']); // admin login

    Route::group(['namespace' => 'App\Http\Controllers\Admin', 'middleware' => 'auth'], function(){
        Route::get('/', 'AdminController@index')->name('welcome');
        Route::get('dashboard', 'AdminController@index')->name('dashboard');
        Route::get('/profile', 'AdminController@showProfile')->name('user.profile');
        Route::get('/profile/{id}/edit', 'AdminController@editProfile')->name('user.edit.profile');
        Route::put('/profile/{id}/update', 'AdminController@updateProfile')->name('user.update.profile');


        //  Roles Control Owner, Admin, Blogwritter
        Route::get('/post/trash', [App\Http\Controllers\Admin\PostController::class, 'trashed'])->name('post.trash');
        Route::get('/post/restore/{id}', [App\Http\Controllers\Admin\PostController::class, 'restore'])->name('post.restore');
        Route::delete('/post/delete/{id}', [App\Http\Controllers\Admin\PostController::class, 'kill'])->name('post.forcedelete');
        Route::get('/post/draft', [App\Http\Controllers\Admin\PostController::class, 'draftPost'])->name('post.draft');
        // Route::delete('/comment/{id}', 'CommentController@destroy')->name('comment.destroy');
        Route::resource('comment-reply', CommentReplyController::class);
        Route::resource('comment', CommentController::class);
        Route::resource('post', PostController::class);

        //  Roles Control Owner, Admin
        Route::resource('category', CategoryController::class);
        Route::resource('tag', TagController::class);

        //  Roles Control Owner
        Route::resource('users', UsersController::class);
        Route::resource('permission', PermissionController::class);
        Route::resource('roles', RolesController::class);
    });
});

routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\CommentReplyController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('comment/{post}', [CommentController::class, 'store'])->name('comment');
Route::delete('comment/{post}', [CommentController::class, 'destroy'])->name('comment_destroy');
Route::post('comment-reply/{comment}', [CommentReplyController::class, 'store'])->name('comment_replay');
Route::delete('comment-reply/{comment}', [CommentReplyController::class, 'destroy'])->name('comment_replay_destroy');

// Users & All Roles Control Panel Routes
Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'App\Http\Controllers\User', 'middleware' => ['auth']], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('posts', 'DashboardController@posts')->name('posts');
    Route::get('posts/read/{slug}', 'DashboardController@read')->name('read');
});
// Owner, Admin & Blogwriter Control Panel Routes
// Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'App\Http\Controllers\Admin', 'middleware' => 'auth'], function(){
//     Route::get('/', 'AdminController@index')->name('welcome');
//     Route::get('dashboard', 'AdminController@index')->name('dashboard');

        //  Roles Control Owner, Admin, Blogwriter
    // Route::resource('post', PostController::class);

        //  Roles Control Owner, Admin
    // Route::resource('category', CategoryController::class);
    // Route::resource('tag', TagController::class);
    
        //  Roles Control Owner,
//     Route::resource('users', UsersController::class);
//     Route::resource('permission', PermissionController::class);
//     Route::resource('roles', RolesController::class);
// });

require __DIR__.'/admin.php';

app/Models/Role.php
<?php

namespace App\Models;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    public $guarded = [];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }
}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\Permission;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\ModelNotFoundException; 

class RolesController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:owner|admin');
    }

    // Roles Listing Page
    public function index()
    {
        //
        $roles = Role::paginate(7);

        $params = [
            'title' => 'Roles Listing',
            'roles' => $roles,
        ];

        return view('admin.roles.roles_list')->with($params);
    }

    // Roles Creation Page
    public function create()
    {
        //
        $permissions = Permission::all();

        $params = [
            'title' => 'Create Roles',
            'permissions' => $permissions,
        ];

        return view('admin.roles.roles_create')->with($params);
    }

    // Roles Store to DB
    public function store(Request $request)
    {
        //
        $this->validate($request, [
            'name' => 'required|unique:roles',
            'display_name' => 'required',
            'description' => 'required',
        ]);

        $role = Role::create([
            'name' => $request->input('name'),
            'display_name' => $request->input('display_name'),
            'description' => $request->input('description'),
        ]);

        return redirect()->route('roles.index')->with('success', "The role <strong>$role->name</strong> has successfully been created.");
    }

    // Roles Delete Confirmation Page
    public function show($id)
    {
        //
        try {
            $role = Role::findOrFail($id);

            $params = [
                'title' => 'Delete Role',
                'role' => $role,
            ];

            return view('admin.roles.roles_delete')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    // Roles Editing Page
    public function edit($id)
    {
        //
        try {
            $role = Role::findOrFail($id);
            $permissions = Permission::all();
            $role_permissions = $role->permissions()->get()->pluck('id')->toArray();

            $params = [
                'title' => 'Edit Role',
                'role' => $role,
                'permissions' => $permissions,
                'role_permissions' => $role_permissions,
            ];

            return view('admin.roles.roles_edit')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    // Roles Update to DB
    public function update(Request $request, $id)
    {
        //
        try {
            $role = Role::findOrFail($id);

            $this->validate($request, [
                'display_name' => 'required',
                'description' => 'required',
            ]);

            $role->name = $request->input('name');
            $role->display_name = $request->input('display_name');
            $role->description = $request->input('description');

            $role->save();

            DB::table("permission_role")->where("permission_role.role_id", $id)->delete();
            // Attach permission to role
            foreach ($request->input('permission_id') as $key => $value) {
                $role->attachPermission($value);
            }

            return redirect()->route('roles.index')->with('success', "The role <strong>$role->name</strong> has successfully been updated.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    // Delete Roles from DB
    public function destroy($id)
    {
        //
        try {
            $role = Role::findOrFail($id);

            //$role->delete();

            // Force Delete
            $role->users()->sync([]); // Delete relationship data
            $role->permissions()->sync([]); // Delete relationship data

            $role->forceDelete(); // Now force delete will work regardless of whether the pivot table has cascading delete

            return redirect()->route('roles.index')->with('success', "The Role <strong>$role->name</strong> has successfully been delete.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }
}

resources/views/admin/roles/roles_create.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Role')
@section('location', 'Role / Create')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <a href="{{route('admin.roles.index')}}" class="btn btn-info">Back</a>
                <h4 class="ml-3">{{$title}}</h4>
            </div>
            <div class="card-body">
                <form method="post" action="{{ route('admin.roles.store') }}" data-parsley-validate class="form-horizontal form-label-left">

                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} row">
                        <label for="name" class="col-sm-2 col-form-label">Name</label>
                        <div class="col-sm-10">
                            <input type="text" value="{{ Request::old('name') ?: '' }}" id="name" name="name" class="form-control col-md-7 col-xs-12"> @if ($errors->has('name'))
                            <span class="help-block">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }} row">
                        <label for="display_name" class="col-sm-2 col-form-label">Display Name</label>
                        <div class="col-sm-10">
                            <input type="text" value="{{ Request::old('display_name') ?: '' }}" id="display_name" name="display_name" class="form-control col-md-7 col-xs-12"> @if ($errors->has('display_name'))
                            <span class="help-block">{{ $errors->first('display_name') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }} row">
                        <label for="description" class="col-sm-2 col-form-label">description</label>
                        <div class="col-sm-10">
                            <input type="text" value="{{ Request::old('description') ?: '' }}" id="description" name="description" class="form-control col-md-7 col-xs-12"> @if ($errors->has('description'))
                            <span class="help-block">{{ $errors->first('description') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="ln_solid"></div>

                    <div class="form-group">
                        <div class="col-sm-2 col-form-label text-md-right">
                            <input type="hidden" name="_token" value="{{ Session::token() }}">
                            <button type="submit" class="btn btn-primary">Create Role</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/roles_delete.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Roles')
@section('location', 'Roles / Delete')
@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <a class="btn btn-sm btn-primary" href="{{route('admin.roles.index')}}">Back</a>
                <h4 class="ml-3">{{$title}}</h4>
            </div>
            <div class="card-body">
                <p>Are you sure you want to delete
                    <strong><u>{{$role->name}}</u></strong>
                </p>
                <form method="POST" action="{{ route('admin.roles.destroy', $role->id) }}">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    <input name="_method" type="hidden" value="DELETE">
                    <button type="submit" class="btn btn-danger">Yes I'm sure. Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/roles/roles_edit.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Roles')
@section('location', 'Roles / Edit')
@section('content')

{{-- <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4"> --}}

<form method="post" action="{{ route('admin.roles.update', $role->id) }}" data-parsley-validate>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{route('admin.roles.index')}}" class="btn btn-info">Back</a>
                    <h4 class="ml-3">Role Users</h4>
                </div>
                <div class="card-body">
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} row">
                        <label for="name" class="col-sm-2 col-form-label">Name</label>
                        <div class="col-sm-10">
                            <input type="text" value="{{$role->name}}" id="name" name="name" class="form-control col-md-7 col-xs-12"> @if ($errors->has('name'))
                            <span class="help-block">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }} row">
                        <label for="display_name" class="col-sm-2 col-form-label">Display Name</label>
                        <div class="col-sm-10">
                            <input type="text" value="{{$role->display_name}}" id="display_name" name="display_name" class="form-control col-md-7 col-xs-12"> @if ($errors->has('display_name'))
                            <span class="help-block">{{ $errors->first('display_name') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }} row">
                        <label for="description" class="col-sm-2 col-form-label">Description</label>
                        <div class="col-sm-10">
                            <input type="text" value="{{$role->description}}" id="description" name="description" class="form-control col-md-7 col-xs-12"> @if ($errors->has('description'))
                            <span class="help-block">{{ $errors->first('description') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('permission_id') ? ' has-error' : '' }} row">
                        <label for="permission_id" class="col-sm-2 col-form-label">Permission</label>
                        <div class="col-md-6 form-check form-check-inline">
                            <ul>
                                @if(count($permissions))
                                    @foreach($permissions as $row)
                                    <label class="form-check-input">{{ Form::checkbox('permission_id[]', $row->id, in_array($row->id, $role_permissions) ? true : false, array('class' => 'name')) }}
                                            {{ $row->display_name }}</label>
                                    @endforeach
                                @endif
                                @if ($errors->has('permission_id'))
                                <span class="help-block">{{ $errors->first('permission_id') }}</span>
                                @endif
                            </ul>
                        </div>
                    </div>

                    <div class="ln_solid"></div>

                    <div class="form-group">
                        <div class="col-sm-2 col-form-label text-md-right">
                            <input type="hidden" name="_token" value="{{ Session::token() }}">
                            <input name="_method" type="hidden" value="PUT">
                            <button type="submit" class="btn btn-primary">Update Now</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/admin/roles/roles_list.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Role')
@section('location', 'Role')
@section('content')

    <a class="btn btn-sm btn-info mb-2" href="{{route('admin.roles.create')}}">Add New Role</a>
      <div class="card">
        <div class="card-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Role Display</th>
                <th scope="col">Role Description</th>
                <th scope="col">Role</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                @foreach($roles as $role)
                <tr>
                  <td>{{ $role->display_name }}</td>
                  <td>{{ $role->description }}</td>
                  <td>{{ $role->name }}</td>
                  <td>
                    <div>
                      <a class="btn btn-primary" href="{{ route('admin.roles.edit', $role->id) }}" class="btn btn-info" data-toggle="tooltip" title="Edit"><i class="fas fa-edit"></i></a>
                      <a class="btn btn-danger" href="{{ route('admin.roles.show', $role->id) }}" class="btn btn-danger" data-toggle="tooltip" title="Delete"><i class="fas fa-trash-alt"></i></a>
                    </div>
                  </td>
                </tr>
                @endforeach
            </tbody>
          </table>
          <div class="clearfix mt-4">
            {{$roles->links('vendor.pagination.bootstrap-4')}}
          </div>
        </div>
      </div>
@endsection