routes/admin.php
<?php 

use App\Http\Controllers\Admin\AuthController;
// use App\Http\Controllers\Admin\CommentController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->name('admin.')->group(function() {
    Route::view('/login', 'auth.login'); 
    Route::post('/login', [AuthController::class, 'store']); // admin login

    Route::group(['namespace' => 'App\Http\Controllers\Admin', 'middleware' => 'auth'], function(){
        Route::get('/', 'AdminController@index')->name('welcome');
        Route::get('dashboard', 'AdminController@index')->name('dashboard');
        Route::get('/profile', 'AdminController@showProfile')->name('user.profile');
        Route::get('/profile/{id}/edit', 'AdminController@editProfile')->name('user.edit.profile');
        Route::put('/profile/{id}/update', 'AdminController@updateProfile')->name('user.update.profile');


        //  Roles Control Owner, Admin, Blogwritter
        Route::get('/post/trash', [App\Http\Controllers\Admin\PostController::class, 'trashed'])->name('post.trash');
        Route::get('/post/restore/{id}', [App\Http\Controllers\Admin\PostController::class, 'restore'])->name('post.restore');
        Route::delete('/post/delete/{id}', [App\Http\Controllers\Admin\PostController::class, 'kill'])->name('post.forcedelete');
        Route::get('/post/draft', [App\Http\Controllers\Admin\PostController::class, 'draftPost'])->name('post.draft');
        // Route::delete('/comment/{id}', 'CommentController@destroy')->name('comment.destroy');
        Route::resource('comment-reply', CommentReplyController::class);
        Route::resource('comment', CommentController::class);
        Route::resource('post', PostController::class);

        //  Roles Control Owner, Admin
        Route::resource('category', CategoryController::class);
        Route::resource('tag', TagController::class);

        //  Roles Control Owner
        Route::resource('users', UsersController::class);
        Route::resource('permission', PermissionController::class);
        Route::resource('roles', RolesController::class);
    });
});

routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\CommentReplyController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('comment/{post}', [CommentController::class, 'store'])->name('comment');
Route::delete('comment/{post}', [CommentController::class, 'destroy'])->name('comment_destroy');
Route::post('comment-reply/{comment}', [CommentReplyController::class, 'store'])->name('comment_replay');
Route::delete('comment-reply/{comment}', [CommentReplyController::class, 'destroy'])->name('comment_replay_destroy');

// Users & All Roles Control Panel Routes
Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'App\Http\Controllers\User', 'middleware' => ['auth']], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('posts', 'DashboardController@posts')->name('posts');
    Route::get('posts/read/{slug}', 'DashboardController@read')->name('read');
});
// Owner, Admin & Blogwriter Control Panel Routes
// Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'App\Http\Controllers\Admin', 'middleware' => 'auth'], function(){
//     Route::get('/', 'AdminController@index')->name('welcome');
//     Route::get('dashboard', 'AdminController@index')->name('dashboard');

        //  Roles Control Owner, Admin, Blogwriter
    // Route::resource('post', PostController::class);

        //  Roles Control Owner, Admin
    // Route::resource('category', CategoryController::class);
    // Route::resource('tag', TagController::class);
    
        //  Roles Control Owner,
//     Route::resource('users', UsersController::class);
//     Route::resource('permission', PermissionController::class);
//     Route::resource('roles', RolesController::class);
// });

require __DIR__.'/admin.php';

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Null_;

class Post extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = ['title', 'category_id', 'user_id', 'content', 'gambar', 'slug'];
    public $timestamps = true;

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getUrlAttribute(){
        $hasMedia =  $this->getMedia('gambar')->first();
        return $hasMedia != null ?
            $hasMedia->getUrl() : "";
    }

    public function category(){
        return $this->belongsTo('App\Models\Category');
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function tags(){
        return $this->belongsToMany('App\Models\Tag');
    }

    public function comments(){
        return $this->hasMany('App\Models\Comment');
    }

    // public function getTotalComments(){
    //     return $this->comments->count();
    // }
    
    // public function replies()
    // {
    //     return $this->hasMany('App\Models\CommentReply');
    // }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\Category;
use App\Models\Tag;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:owner|admin|blogwriter');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::with('posts')->get();
        $posts = Post:: where('status', 'publish')
                        ->orderBy('created_at', 'desc')->paginate(8);
        return view('admin.post.index', compact('posts','tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        $posts = Post::paginate(8);
        return view('admin.post.create', compact('posts', 'tags', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $this->validate($request,[
            'title' => 'required',
            'category_id' => 'required',
            'status' => 'required',
            'content' => 'required',
            'gambar' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:1048',
        ]);
        

        if ($request->hasFile('gambar')) {
            // request file
            $gambar = $request->file('gambar');
            // rename file with math
            $math = rand(10000, 99999);
            // named file
            $image_name = time(). + $math.'.'.$gambar->extension();
            // request path disk file 
            $request->gambar->storeAs('post', $image_name, 'public');
        } else {
            $image_name = 'noThumbnail.png';
        }

        // Checking value status 

        // if ($request->status  != 'draft') {
        //     dd('Hooolaaaaa Publish!');
        // } else {
        //     dd('Hooolaaaaa Draft!');
        // }
        
        
        // $gambar = $request->file('gambar');
        // $math = rand(10000, 99999);
        // $image_name = time(). + $math.'.'.$gambar->extension();
        // $request->gambar->storeAs('post', $image_name, 'public');

        $posts = new Post();
        $posts->title = $request->input('title');
        $posts->slug = str_slug( $request->input('title'));
        $posts->category_id = $request->input('category_id');
        $posts->content = $request->input('content');
        $posts->status = $request->input('status');
        $posts->gambar = $image_name;
        $posts->user_id = Auth::user()->id;
        // dd($posts);
        $posts->save();

        $posts->tags()->attach($request->tags);
        return redirect()->back()->with('success', 'New Post was successfully created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $categories = Category::all();
        $tags = Tag::all();
        $posts = Post::where('slug', $slug)->first();
        return view('admin.post.show', compact('posts', 'tags', 'categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $categories = Category::all();
        $tags = Tag::all();
        $posts = Post::where('slug', $slug)->first();
        return view('admin.post.edit', compact('posts', 'tags', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $slug)
    {
        $this->validate($request, [
            'title' => 'required',
            'category_id' => 'required',
            'content' => 'required',
        ]);

        $posts = Post::where('slug', $slug)->first();
        if($request->hasFile('gambar')){
            $gambar = $request->file('gambar');
            $image_name = time().'.'.$gambar->getClientOriginalName();

            // Delete old images
            //

            $request->gambar->storeAs('post', $image_name, 'public');

            $posts->title = $request->input('title');
            $posts->category_id = $request->input('category_id');
            $posts->content = $request->input('content');
            $posts->slug = str_slug($request->input('title'));
            $posts->gambar =$image_name;
        } 
        else {
            $posts->title = $request->input('title');
            $posts->category_id = $request->input('category_id');
            $posts->content = $request->input('content');
            $posts->slug = str_slug($request->input('title'));
        }

        $posts->tags()->sync($request->tags);
        $posts->update();
        
        return redirect('/admin/post')->with('success', 'Post was successfully update!');
    }


    public function draftPost(Request $request){
        // $data = [];
        // $n_draft = Post::where('status', 'draft')
        //                 ->orderBy('created_at', 'desc')
        //                 ->paginate(8);
        // $data = [
        //     'draft' => $n_draft,

        // ];
        $tags = Tag::with('posts')->get();
        $posts = Post:: where('status', 'draft')
                        ->orderBy('created_at', 'desc')
                        ->paginate(8);

        return view('admin.post.draft', compact('tags', 'posts'));
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($slug)
    {
        $posts = Post::where('slug', $slug)->first();
        $posts->delete();

        return redirect()->back()->with('success', 'Post was successfully delete!');
    }

    public function trashed(){
        $posts = Post::onlyTrashed()->paginate(8);
        return view('admin.post.trashed', compact('posts'));
    }

    public function restore($id){
        $posts = Post::withTrashed()->where('id', $id)->first();
        $posts->restore();

        return redirect()->back()->with('success', 'Post was successfully restored!');
    }

    public function kill($id){
        $posts = Post::withTrashed()->where('id', $id)->first();

        //Delete old images from directory file 
        if(file_exists(public_path('storage/post/'))){
            unlink(public_path('storage/post/' .$posts->gambar));
        };

        $posts->forceDelete();

        return redirect()->back()->with('success', 'Post was successfully Delete!');
    }


    // private function statusPost(){
    //     return[
    //         'draft' => trans('posts.form_control.select.status.option.draft'),
    //         'publish' => trans('posts.form_control.select.status.option.publish'),
    //     ];
    // }
}

resources/views/admin/post/create.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Post')
@section('location', 'Post / Add Post')
@push('links')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css"> 

@endpush
@section('content') 
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <a href="{{route('admin.post.index')}}" class="btn btn-info">Back</a>
                <h4 class="ml-3">Add Post</h4>
            </div>
            <div class="card-body">
                <form action="{{route('admin.post.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tittle</label>
                        <div class="col-sm-12 col-md-7">
                            <input type="text" required class="form-control" name="title" placeholder="Create your title..">
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Kategory</label>
                        <div class="col-sm-12 col-md-7">
                            <select class="selectpicker form-control" data-live-search="true" name="category_id" required>
                                <option value="" disabled selected>Select your category</option>
                                @foreach ($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tag</label>
                        <div class="col-sm-12 col-md-7">
                            <select class="selectpicker form-control select2" multiple data-live-search="true" name="tags[]" id="" required>
                                @foreach ($tags as $tag)
                            <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Status</label>
                        <div class="col-sm-12 col-md-7">
                            <select class="selectpicker form-control" data-live-search="true" name="status" required>
                                <option value="" disabled selected>Select status</option>
                                <option value="draft">Draft</option>
                                <option value="publish">Publish</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Content</label>
                        <div class="col-sm-12 col-md-7">
                            <textarea name="content" id="content" cols="73" rows="4" class="form-control" placeholder="Create your content.." required></textarea>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Thumbnail <i class="fas fa-info-circle ml-2" data-toggle="tooltip" data-placement="top" title="Max 1 Mb" style="cursor: pointer"></i> </label>
                        <div class="col-sm-12 col-md-7">
                            <input type="file" class="form-control" name="gambar" onchange="previewFile(this)" required/>
                            <img id="previewImg" src="" alt="" style="max-width: 130px;margin-top: 20px;max-height: 130px;" />
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                        <div class="col-sm-12 col-md-7">
                            <button class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
@endpush

resources/views/admin/post/draft.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Post')
@section('location', 'Post')
@section('content') 
    <div class="clearfix mt-4">
        <a href="{{route('admin.post.create')}}" class="btn btn-info mb-2">Create Post</a>
        
    </div>
    
    <div class="card">
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">No</th>
                        <th scope="col">Created at</th>
                        <th scope="col">Name Post</th>
                        <th scope="col">Kategory</th>
                        <th scope="col">Status</th>
                        <th scope="col">Thumbnail</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    @if (count($posts) > 0)
                    @foreach ($posts as $key => $post)
                    <tbody>
                    <tr>
                        {{-- <th scope="row">{{ $post->id }}</th> --}}
                        <td>{{ $key+1 }}.</td>
                        <td>{{ $post->created_at->format('d/m/Y') }}</td>
                        <td>
                            {{ $post->title }}
                            <div class="table-links">
                                by <a href="#">{{$post->user->name}}</a>
                                <div class="bullet"></div>
                                <a href="{{route('admin.post.show', $post->slug)}}">View</a>
                            </div>
                        </td>
                        <td>{{ $post->category->name }}</td>
                        <td>
                            <div class="buttons">
                                @if ($post->status != 'draft')
                                <a href="#" class="btn btn-icon btn-sm btn-success">publish{{--<i class="fas fa-check"></i>--}}</a>
                                @else
                                <a href="#" class="btn btn-icon btn-sm btn-warning">draft{{--<i class="fas fa-times"></i>--}}</a>
                                @endif
                            </div>
                                
                                
                        </td>
                    <td><img src="{{ asset('storage/post/'.$post->gambar) }}" alt="{{ $post->judul }}" style="max-width: 50px;margin-top: 2px;"></td>
                        <td>
                        <form action="{{route('admin.post.destroy', $post->slug) }}" method="POST">
                            @csrf
                            @method('delete')
                            <a class="btn btn-info" href="{{ route('admin.post.show', $post->slug) }}" data-toggle="tooltip" title="View"><i class="fas fa-eye"></i> </a>
                            <a href="{{route('admin.post.edit', $post->slug) }}" class="btn btn-primary btn-action " data-toggle="tooltip" title="Edit"><i class="fas fa-edit"></i></a>
                            <button type="submit" class="btn btn-danger btn-action" data-toggle="tooltip" title="Delete"><i class="fas fa-trash-alt"></i></button>
                        </form>
                        </td>
                    </tr>
                    </tbody>
                    @endforeach
                    @else
                        <td colspan="6" class="text-center" style="color: #6777ef;">                           
                            <b>Post not found. <a href="{{route('admin.post.create')}}" style="font-weight: bold;">Create here!</a></b>
                        </td>
                    @endif
            </table>
        </div>
    </div>
    <!-- Pager -->
    <div class="clearfix mt-4">
        {{$posts->links('vendor.pagination.bootstrap-4')}}
    </div>
@endsection

resources/views/admin/post/edit.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Post')
@section('location', 'Post / Edit Post')
@push('links')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css"> 
@endpush
@section('content') 
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <a href="{{route('admin.post.index')}}" class="btn btn-info">Back</a>
                <h4 class="ml-3">Edit Post</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('admin.post.update', $posts->slug) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tittle</label>
                        <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control" name="title" placeholder="Create your title.." value="{{$posts->title}}">
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Kategory</label>
                        <div class="col-sm-12 col-md-7">
                            <select class="selectpicker form-control" data-live-search="true" name="category_id">
                                <option value="" holder>Select your category</option>
                                @foreach ($categories as $category)
                            <option value="{{ $category->id }}"
                                @if ($posts->category_id == $category->id)
                                    selected
                                @endif
                                >{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tag</label>
                        <div class="col-sm-12 col-md-7">
                            <select class="selectpicker form-control select2" multiple data-live-search="true" name="tags[]" id="" required>
                                @foreach ($tags as $tag)
                            <option value="{{ $tag->id }}"
                                @foreach ($posts->tags as $item)
                                    @if ($tag->id == $item->id)
                                        selected
                                    @endif
                                @endforeach
                                >{{ $tag->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Content</label>
                        <div class="col-sm-12 col-md-7">
                        <textarea name="content" id="content" cols="73" rows="4" class="form-control" placeholder="Create your content..">{{ $posts->content }}</textarea>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Thumbnail</label>
                        <div class="col-sm-12 col-md-7">
                            <input type="file" class="form-control" name="gambar" onchange="previewFile(this)" />
                            <img id="previewImg" src="{{asset('storage/post/')}}/{{$posts->gambar}}" alt="" style="max-width: 130px;margin-top: 20px;max-height: 130px;" />
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                        <div class="col-sm-12 col-md-7">
                            <button class="btn btn-primary">Update Now</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
@endpush

resources/views/admin/post/trashed.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Trash Bin')
@section('location', 'Trash Bin')
@section('content') 

    <div class="card">
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">No.</th>
                        <th scope="col">Date</th>
                        <th scope="col">Name Post</th>
                        <th scope="col">Kategory</th>
                        <th scope="col">Cover</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    @if (count($posts) > 0)
                    @foreach ($posts as $key => $post)
                    <tbody>
                    <tr>
                        <th scope="row">{{ $key+1 }}</th>
                        <td>{{ $post->created_at->format('d/m/Y') }}</td>
                        <td><a href="">{{ $post->title }}</a></td>
                        <td>{{ $post->category->name }}</td>
                    <td><img src="{{ asset('images/'.$post->gambar) }}" alt="{{ $post->judul }}" style="max-width: 50px;margin-top: 2px;"></td>
                        <td>
                        <form action="{{route('admin.post.forcedelete', $post->id) }}" method="POST">
                            @csrf
                            @method('delete')
                            <a href="{{route('admin.post.restore', $post->id) }}" class="btn btn-primary btn-action " data-toggle="tooltip" title="Restored"><i class="fas fa-reply"></i></a>
                            <button type="submit" class="btn btn-danger btn-action" data-toggle="tooltip" title="Delete"><i class="fas fa-trash-alt"></i></button>
                        </form>
                        </td>
                    </tr>
                    </tbody>
                    @endforeach
                    @else
                        <td colspan="6" class="text-center" style="color: #6777ef;">                           
                            <b>No items here.</b>
                        </td>
                    @endif
            </table>
        </div>
    </div>
    <!-- Pager -->
    <div class="clearfix mt-4">
        {{$posts->links('vendor.pagination.bootstrap-4')}}
    </div>
@endsection