routes/admin.php
<?php 

use App\Http\Controllers\Admin\AuthController;
// use App\Http\Controllers\Admin\CommentController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->name('admin.')->group(function() {
    Route::view('/login', 'auth.login'); 
    Route::post('/login', [AuthController::class, 'store']); // admin login

    Route::group(['namespace' => 'App\Http\Controllers\Admin', 'middleware' => 'auth'], function(){
        Route::get('/', 'AdminController@index')->name('welcome');
        Route::get('dashboard', 'AdminController@index')->name('dashboard');
        Route::get('/profile', 'AdminController@showProfile')->name('user.profile');
        Route::get('/profile/{id}/edit', 'AdminController@editProfile')->name('user.edit.profile');
        Route::put('/profile/{id}/update', 'AdminController@updateProfile')->name('user.update.profile');


        //  Roles Control Owner, Admin, Blogwritter
        Route::get('/post/trash', [App\Http\Controllers\Admin\PostController::class, 'trashed'])->name('post.trash');
        Route::get('/post/restore/{id}', [App\Http\Controllers\Admin\PostController::class, 'restore'])->name('post.restore');
        Route::delete('/post/delete/{id}', [App\Http\Controllers\Admin\PostController::class, 'kill'])->name('post.forcedelete');
        Route::get('/post/draft', [App\Http\Controllers\Admin\PostController::class, 'draftPost'])->name('post.draft');
        // Route::delete('/comment/{id}', 'CommentController@destroy')->name('comment.destroy');
        Route::resource('comment-reply', CommentReplyController::class);
        Route::resource('comment', CommentController::class);
        Route::resource('post', PostController::class);

        //  Roles Control Owner, Admin
        Route::resource('category', CategoryController::class);
        Route::resource('tag', TagController::class);

        //  Roles Control Owner
        Route::resource('users', UsersController::class);
        Route::resource('permission', PermissionController::class);
        Route::resource('roles', RolesController::class);
    });
});

routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\CommentReplyController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('comment/{post}', [CommentController::class, 'store'])->name('comment');
Route::delete('comment/{post}', [CommentController::class, 'destroy'])->name('comment_destroy');
Route::post('comment-reply/{comment}', [CommentReplyController::class, 'store'])->name('comment_replay');
Route::delete('comment-reply/{comment}', [CommentReplyController::class, 'destroy'])->name('comment_replay_destroy');

// Users & All Roles Control Panel Routes
Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'App\Http\Controllers\User', 'middleware' => ['auth']], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('posts', 'DashboardController@posts')->name('posts');
    Route::get('posts/read/{slug}', 'DashboardController@read')->name('read');
});
// Owner, Admin & Blogwriter Control Panel Routes
// Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'App\Http\Controllers\Admin', 'middleware' => 'auth'], function(){
//     Route::get('/', 'AdminController@index')->name('welcome');
//     Route::get('dashboard', 'AdminController@index')->name('dashboard');

        //  Roles Control Owner, Admin, Blogwriter
    // Route::resource('post', PostController::class);

        //  Roles Control Owner, Admin
    // Route::resource('category', CategoryController::class);
    // Route::resource('tag', TagController::class);
    
        //  Roles Control Owner,
//     Route::resource('users', UsersController::class);
//     Route::resource('permission', PermissionController::class);
//     Route::resource('roles', RolesController::class);
// });

require __DIR__.'/admin.php';

app/Models/Permission.php
<?php

namespace App\Models;

use Laratrust\Models\LaratrustPermission;

class Permission extends LaratrustPermission
{
    public $guarded = [];

    public function user() {
        return $this->belongsToMany(Role::class);
    }

    public function roles() {
        return $this->belongsToMany(Permission::class);
    }
}

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Role;
use App\Models\Permission;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\ModelNotFoundException; 


class PermissionController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:owner|admin');
    }

    // Permission Listing Page
    public function index()
    {
        //
        $permissions = Permission::paginate(7);
        //dd($users);

        $params = [
            'title' => 'Permissions Listing',
            'permissions' => $permissions,
        ];

        return view('admin.permission.perm_list')->with($params);
    }

    // Permission Create Page
    public function create()
    {
        //
        $params = [
            'title' => 'Create Permission',
        ];

        return view('admin.permission.perm_create')->with($params);
    }

    // Permission Store to DB
    public function store(Request $request)
    {
        //
        $this->validate($request, [
            'name' => 'required|unique:permissions',
            'display_name' => 'required',
            'description' => 'required',
        ]);

        $permission = Permission::create([
            'name' => $request->input('name'),
            'display_name' => $request->input('display_name'),
            'description' => $request->input('description'),
        ]);

        return redirect()->route('permission.index')->with('success', "The Permission <strong>$permission->name</strong> has successfully been created.");
    }

    // Permission Delete Confirmation Page
    public function show($id)
    {
        //
        try {
            $permission = Permission::findOrFail($id);

            $params = [
                'title' => 'Delete Permission',
                'permission' => $permission,
            ];

            return view('admin.permission.perm_delete')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    // Permission Editing Page
    public function edit($id)
    {
        //
        try {
            $permission = Permission::findOrFail($id);

            $params = [
                'title' => 'Edit Permission',
                'permission' => $permission,
            ];

            //dd($role_permissions);

            return view('admin.permission.perm_edit')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    // Permission update to DB
    public function update(Request $request, $id)
    {
        //
        try {
            $permission = Permission::findOrFail($id);

            $this->validate($request, [
                'display_name' => 'required',
                'description' => 'required',
            ]);

            $permission->name = $request->input('name');
            $permission->display_name = $request->input('display_name');
            $permission->description = $request->input('description');

            $permission->save();

            return redirect()->route('permission.index')->with('success', "The permission <strong>$permission->name</strong> has successfully been updated.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    // Permission Delete from DB
    public function destroy($id)
    {
        //
        try {
            $permission = Permission::findOrFail($id);
            DB::table("permission_role")->where('permission_id', $id)->delete();
            $permission->delete();
            
            return redirect()->route('permission.index')->with('success', "The Role <strong>$permission->name</strong> has successfully been archived.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }
}

resources/views/admin/permission/perm_create.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Permissions')
@section('location', 'Permissions / Create')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <a class="btn btn-sm btn-primary" href="{{route('admin.permission.index')}}">Back</a>
                <h4 class="ml-3">{{$title}}</h4>
            </div>
            <div class="card-body">
                <form method="post" action="{{ route('admin.permission.store') }}" data-parsley-validate class="form-horizontal form-label-left">

                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} row">
                        <label for="name" class="col-sm-2 col-form-label">Name</label>
                        <div class="col-sm-10">
                            <input type="text" value="{{ Request::old('name') ?: '' }}" id="name" name="name" class="form-control col-md-7 col-xs-12"> @if ($errors->has('name'))
                            <span class="help-block">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }} row">
                        <label for="display_name" class="col-sm-2 col-form-label">Display Name</label>
                        <div class="col-sm-10">
                            <input type="text" value="{{ Request::old('display_name') ?: '' }}" id="display_name" name="display_name" class="form-control col-md-7 col-xs-12"> @if ($errors->has('display_name'))
                            <span class="help-block">{{ $errors->first('display_name') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }} row">
                        <label for="description" class="col-sm-2 col-form-label">description</label>
                        <div class="col-sm-10">
                            <input type="text" value="{{ Request::old('description') ?: '' }}" id="description" name="description" class="form-control col-md-7 col-xs-12"> @if ($errors->has('description'))
                            <span class="help-block">{{ $errors->first('description') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="ln_solid"></div>

                    <div class="form-group">
                        <div class="col-sm-2 col-form-label text-md-right">
                            <input type="hidden" name="_token" value="{{ Session::token() }}">
                            <button type="submit" class="btn btn-primary">Create Permission</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/permission/perm_delete.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Permissions')
@section('location', 'Permissions / Delete')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <a class="btn btn-sm btn-primary" href="{{route('admin.permission.index')}}">Back</a>
                <h4 class="ml-3">{{$title}}</h4>
            </div>
            <div class="card-body">
                <p>Are you sure you want to delete
                    <strong><u> {{$permission->name}}</u></strong>
                </p>

                <form method="POST" action="{{ route('admin.permission.destroy', $permission->id) }}">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    <input name="_method" type="hidden" value="DELETE">
                    <button type="submit" class="btn btn-danger">Yes I'm sure. Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/permission/perm_edit.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Permissions')
@section('location', 'Permissions / Edit')
@section('content')
<form method="POST" action="{{ route('admin.permission.update', $permission->id) }}" data-parsley-validate>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-sm btn-primary" href="{{route('admin.permission.index')}}">Back</a>
                    <h4 class="ml-3">{{$title}}</h4>
                </div>
                <div class="card-body">
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} row">
                        <label for="name" class="col-sm-2 col-form-label">Name</label>
                        <div class="col-sm-10">
                            <input type="text" value="{{$permission->name}}" id="name" name="name" class="form-control col-md-7 col-xs-12"> @if ($errors->has('name'))
                            <span class="help-block">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }} row">
                        <label for="display_name" class="col-sm-2 col-form-label">Display Name</label>
                        <div class="col-sm-10">
                            <input type="text" value="{{$permission->display_name}}" id="display_name" name="display_name" class="form-control col-md-7 col-xs-12"> @if ($errors->has('display_name'))
                            <span class="help-block">{{ $errors->first('display_name') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }} row">
                        <label for="description" class="col-sm-2 col-form-label">Description</label>
                        <div class="col-sm-10">
                            <input type="text" value="{{$permission->description}}" id="description" name="description" class="form-control col-md-7 col-xs-12"> @if ($errors->has('description'))
                            <span class="help-block">{{ $errors->first('description') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="ln_solid"></div>

                    <div class="form-group">
                        <div class="col-sm-2 col-form-label text-md-right">
                            <input type="hidden" name="_token" value="{{ Session::token() }}">
                            <input name="_method" type="hidden" value="PUT">
                            <button type="submit" class="btn btn-primary">Update Now</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@endsection

resources/views/admin/permission/perm_list.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Permissions')
@section('location', 'Permissions')
@section('content')

<div class="clearfix mt-4">
  <a href="{{route('admin.permission.create')}}" class="btn btn-info mb-2">Add Permission</a>
</div>
      
      {{-- <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Permission</h1>
      </div>
      <a class="btn btn-sm btn-primary" href="{{route('permission.create')}}">Add New Permission</a>
      <h2>{{$title}}</h2> --}}
      <div class="card">
        <div class="card-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Display Name</th>
                <th>Description</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
                @foreach($permissions as $row)
                <tr>
                  <td>{{ $row->name }}</td>
                  <td>{{ $row->display_name }}</td>
                  <td>{{ $row->description }}</td>
                  <td>
                    <div>
                      <a class="btn btn-primary" href="{{ route('admin.permission.edit', $row->id) }}" class="btn btn-info " data-toggle="tooltip" title="Edit"><i class="fas fa-edit"></i> </a>
                      <a class="btn btn-danger" href="{{ route('admin.permission.show', $row->id) }}" class="btn btn-danger " data-toggle="tooltip" title="Delete"><i class="fas fa-trash-alt"></i> </a>
                    </div>
                  </td>
                </tr>
                @endforeach
            </tbody>
          </table>
          <!-- Pager -->
          <div class="clearfix mt-4">
            {{$permissions->links('vendor.pagination.bootstrap-4')}}
          </div>
        </div>
      </div>

@endsection