routes/admin.php
<?php 

use App\Http\Controllers\Admin\AuthController;
// use App\Http\Controllers\Admin\CommentController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->name('admin.')->group(function() {
    Route::view('/login', 'auth.login'); 
    Route::post('/login', [AuthController::class, 'store']); // admin login

    Route::group(['namespace' => 'App\Http\Controllers\Admin', 'middleware' => 'auth'], function(){
        Route::get('/', 'AdminController@index')->name('welcome');
        Route::get('dashboard', 'AdminController@index')->name('dashboard');
        Route::get('/profile', 'AdminController@showProfile')->name('user.profile');
        Route::get('/profile/{id}/edit', 'AdminController@editProfile')->name('user.edit.profile');
        Route::put('/profile/{id}/update', 'AdminController@updateProfile')->name('user.update.profile');


        //  Roles Control Owner, Admin, Blogwritter
        Route::get('/post/trash', [App\Http\Controllers\Admin\PostController::class, 'trashed'])->name('post.trash');
        Route::get('/post/restore/{id}', [App\Http\Controllers\Admin\PostController::class, 'restore'])->name('post.restore');
        Route::delete('/post/delete/{id}', [App\Http\Controllers\Admin\PostController::class, 'kill'])->name('post.forcedelete');
        Route::get('/post/draft', [App\Http\Controllers\Admin\PostController::class, 'draftPost'])->name('post.draft');
        // Route::delete('/comment/{id}', 'CommentController@destroy')->name('comment.destroy');
        Route::resource('comment-reply', CommentReplyController::class);
        Route::resource('comment', CommentController::class);
        Route::resource('post', PostController::class);

        //  Roles Control Owner, Admin
        Route::resource('category', CategoryController::class);
        Route::resource('tag', TagController::class);

        //  Roles Control Owner
        Route::resource('users', UsersController::class);
        Route::resource('permission', PermissionController::class);
        Route::resource('roles', RolesController::class);
    });
});

routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\CommentReplyController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('comment/{post}', [CommentController::class, 'store'])->name('comment');
Route::delete('comment/{post}', [CommentController::class, 'destroy'])->name('comment_destroy');
Route::post('comment-reply/{comment}', [CommentReplyController::class, 'store'])->name('comment_replay');
Route::delete('comment-reply/{comment}', [CommentReplyController::class, 'destroy'])->name('comment_replay_destroy');

// Users & All Roles Control Panel Routes
Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'App\Http\Controllers\User', 'middleware' => ['auth']], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('posts', 'DashboardController@posts')->name('posts');
    Route::get('posts/read/{slug}', 'DashboardController@read')->name('read');
});
// Owner, Admin & Blogwriter Control Panel Routes
// Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'App\Http\Controllers\Admin', 'middleware' => 'auth'], function(){
//     Route::get('/', 'AdminController@index')->name('welcome');
//     Route::get('dashboard', 'AdminController@index')->name('dashboard');

        //  Roles Control Owner, Admin, Blogwriter
    // Route::resource('post', PostController::class);

        //  Roles Control Owner, Admin
    // Route::resource('category', CategoryController::class);
    // Route::resource('tag', TagController::class);
    
        //  Roles Control Owner,
//     Route::resource('users', UsersController::class);
//     Route::resource('permission', PermissionController::class);
//     Route::resource('roles', RolesController::class);
// });

require __DIR__.'/admin.php';

resources/views/layouts/admin/component/content.blade.php
@section('sub-title', 'Dashboard')
@section('location', 'Dashboard')
<div class="main-content">
    <section class="section">
    <div class="section-header">
        <div class="col-sm-6">
            <h1>@yield('location')</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Home</a></li>
            <li class="breadcrumb-item active">@yield('location')</li>
            </ol>
        </div>
    </div>
    @include('include.message')
    @yield('content')
    </section>
</div>

resources/views/layouts/admin/component/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; 2021 by <a href="https://farghani.com/">Agung Prasetyo</a> <div class="bullet"></div> Thanks and Design By <a href="https://nauval.in/">Muhamad Nauval Azhar</a>
    </div>
    <div class="footer-right">
    
    </div>
</footer>

resources/views/layouts/admin/component/loader.blade.php
<div class="loader">


    <div class="s1">
        <div class="s b sb1"></div>
        <div class="s b sb2"></div>
        <div class="s b sb3"></div>
        <div class="s b sb4"></div>
    </div>


    <div class="s2">
        <div class="s b sb5"></div>
        <div class="s b sb6"></div>
        <div class="s b sb7"></div>
        <div class="s b sb8"></div>
    </div>

    <div class="bigcon">
        <div class="big b"></div>
    </div>

    <div class="agung-loader">
        <div class="text-loader">
            <h2>Kami siap-siap dulu, ya...</h2>
        </div>
    </div>

</div>

resources/views/layouts/admin/component/navbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
        </ul>
        <div class="search-element">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
        <button class="btn" type="submit"><i class="fas fa-search"></i></button>
        <div class="search-backdrop"></div>
        <div class="search-result">
            <div class="search-header">
            Histories
            </div>
            <div class="search-item">
            <a href="#">How to hack NASA using CSS</a>
            <a href="#" class="search-close"><i class="fas fa-times"></i></a>
            </div>
            <div class="search-item">
            <a href="#">Kodinger.com</a>
            <a href="#" class="search-close"><i class="fas fa-times"></i></a>
            </div>
            <div class="search-item">
            <a href="#">#Stisla</a>
            <a href="#" class="search-close"><i class="fas fa-times"></i></a>
            </div>
            <div class="search-header">
            Result
            </div>
            <div class="search-item">
            <a href="#">
                <img class="mr-3 rounded" width="30" src="{{ asset('assets/img/products/product-3-50.png') }}" alt="product">
                oPhone S9 Limited Edition
            </a>
            </div>
            <div class="search-item">
            <a href="#">
                <img class="mr-3 rounded" width="30" src="{{ asset('assets/img/products/product-2-50.png') }}" alt="product">
                Drone X2 New Gen-7
            </a>
            </div>
            <div class="search-item">
            <a href="#">
                <img class="mr-3 rounded" width="30" src="{{ asset('assets/img/products/product-1-50.png') }}" alt="product">
                Headphone Blitz
            </a>
            </div>
            <div class="search-header">
            Projects
            </div>
            <div class="search-item">
            <a href="#">
                <div class="search-icon bg-danger text-white mr-3">
                <i class="fas fa-code"></i>
                </div>
                Stisla Admin Template
            </a>
            </div>
            <div class="search-item">
            <a href="#">
                <div class="search-icon bg-primary text-white mr-3">
                <i class="fas fa-laptop"></i>
                </div>
                Create a new Homepage Design
            </a>
            </div>
        </div>
        </div>
    </form>
    <ul class="navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                @if (file_exists('storage/photo/'.Auth::user()->photo))
                <img alt="image" src="{{ asset('storage/photo/'.Auth::user()->photo) }}" class="rounded-circle mr-1">
                @endif
                <div class="d-sm-none d-lg-inline-block">Hi, {{ Auth::user()->name }}</div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-title" style="font-size: 8px">Logged in {{ Auth::User()->current_sign_in_at->diffForHumans() }}</div>
                    <a href="{{url('/admin/profile')}}" class="dropdown-item has-icon">
                        <i class="far fa-user"></i> Profile
                    </a>
                    <a href="features-activities.html" class="dropdown-item has-icon">
                        <i class="fas fa-bolt"></i> Activities
                    </a>
                    <a href="features-settings.html" class="dropdown-item has-icon">
                        <i class="fas fa-cog"></i> Settings
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger"
                        onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                        <i class="fas fa-sign-out-alt"></i> 
                        {{ __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/admin/component/sidebar_menu.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
      <div class="sidebar-brand">
        <a href="{{route('home')}}">{{ config('app.name') }}</a>
      </div>
      <div class="sidebar-brand sidebar-brand-sm">
        <a href="{{route('home')}}">FN</a>
      </div>
      <ul class="sidebar-menu">
        @role(['owner','admin', 'blogwriter'])
          <li class="menu-header">Dashboard Menu</li>
          <li class="nav-item dropdown">
          <a href="{{route('admin.dashboard')}}" class="nav-link {{ Request::is('dashboard') ? ' active' : null }}"><i class="fas fa-fire"></i><span>Dashboard</span></a>
          </li>
          {{-- <li class="menu-header">Starter</li> --}}
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-newspaper"></i> <span>Post</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link beep beep-sidebar" href="{{route('admin.post.create')}}"><i class="far fa-plus-square" style="margin: 0"></i>Add Post</a></li>
              <li><a class="nav-link" href="{{route('admin.post.index')}}"><i class="fas fa-list-ul" style="margin: 0"></i>List Post</a></li>
              <li><a class="nav-link" href="{{route('admin.post.draft')}}"><i class="fas fa-list-ul" style="margin: 0"></i>Draft Post</a></li>
              <li><a class="nav-link" href="{{route('admin.comment.index')}}"><i class="far fa-comment" style="margin: 0"></i>Post Comment</a></li>
              <li><a class="nav-link" href="{{route('admin.comment-reply.index')}}"><i class="far fa-comments" style="margin: 0"></i>Post Comment reply</a></li>
            </ul>
          </li>
          
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-stream"></i> <span>Kategory</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link beep beep-sidebar" href="{{route('admin.category.create')}}"><i class="far fa-plus-square" style="margin: 0"></i>Add Kategory</a></li>
              <li><a class="nav-link" href="{{route('admin.category.index')}}"><i class="fas fa-list-ul" style="margin: 0"></i>List Kategory</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fab fa-slack-hash"></i> <span>Tag</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link beep beep-sidebar" href="{{route('admin.tag.create')}}"><i class="far fa-plus-square" style="margin: 0"></i>Add Tags</a></li>
              <li><a class="nav-link" href="{{route('admin.tag.index')}}"><i class="fas fa-list-ul" style="margin: 0"></i>List Tags</a></li>
            </ul>
          </li>
          @role(['owner','admin'])
            <li class="menu-header">SDM & Permissions</li>
            <li><a class="nav-link" href="{{route('admin.users.index')}}"><i class="fas fa-user"></i> <span>Users</span></a></li>
          @endrole
          @role(['owner'])
            <li><a class="nav-link" href="{{route('admin.roles.index')}}"><i class="fas fa-eye-slash"></i> <span>Roles</span></a></li>
            <li><a class="nav-link" href="{{route('admin.permission.index')}}"><i class="fas fa-info"></i> <span>Permissions</span></a></li>
            <li><a class="nav-link" href="{{route('admin.post.trash')}}"><i class="far fa-trash-alt"></i> <span>Trash Bin</span></a></li>
          @endrole
          @endrole
        </ul>

        <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
          <a href="{{ url('/') }}" class="btn btn-primary btn-lg btn-block btn-icon-split">
            <i class="fas fa-rocket"></i> {{ config('app.name') }}
          </a>
        </div> 
    </aside>
  </div>